"""Add description column to HandOver (fixed)

Revision ID: 0a06fe2b373f
Revises: 0c7584da4bfb
Create Date: 2025-09-25 18:08:43.918615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a06fe2b373f'
down_revision = '0c7584da4bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hand_over', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False,server_default='N/A'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hand_over', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
